# Generated by Django 3.2.4 on 2021-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_profile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.FileField(null=True, upload_to='user_profile_images/'),
        ),
    ]
